#!/usr/bin/env bash

set -eu

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

function usage
{
  echo "usage: $0 <about|donate> [<in dir> <out dir>]"
  exit 1
}

[ $# -eq 1 -o $# -eq 3 ] || usage

paste=$1
in=${2:-$dir/../src/paste}
out=${3:-$dir/../paste}

# $1 => input file
# $2 => output file
# $3 => secret key
function encrypt
{
  openssl aes-256-cbc -pass pass:$3 -in "$1" -out "$2"
  touch -c -m -t 210012250000 "$2" # Christmas, year 2100
  echo "encrypted paste written to $2"
}

case "$paste" in
  'about')
    encrypt "$in/$paste" \
            "$out/14e3c3ce" \
            "371864573d2a445868316521cc3cc374413f3eb04978281c964527cdc79a64bb"
    ;;
  'donate')
    encrypt "$in/$paste" \
            "$out/f1a8f535" \
            "31bcdb56b77528a3c1b540bc460ed07d5b74fcf65eb91733bc4d10884e764caf"
    ;;
  *)
    usage
    ;;
esac
