#!/usr/bin/env bash

set -eu

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

function usage
{
  echo "usage: $0 about|donate"
  exit 1
}

[ ! $# -eq 1 ] && usage

# $1 => input file
# $2 => output file
function encrypt
{
  openssl aes-256-cbc -in "$1" -out "$2"
  touch -c -m -t 210012250000 "$2" # Christmas, year 2100
}

case "$1" in
  'about')
    echo "371864573d2a445868316521cc3cc374413f3eb04978281c964527cdc79a64bb"
    encrypt "$dir/../src/paste/about" "$dir/../paste/14e3c3ce"
    ;;
  'donate')
    echo "31bcdb56b77528a3c1b540bc460ed07d5b74fcf65eb91733bc4d10884e764caf"
    encrypt "$dir/../src/paste/about" "$dir/../paste/f1a8f535"
    ;;
  *)
    usage
    ;;
esac
